apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    role: maiRole
spec:
  replicas: 4
  selector:
    matchLabels:
      role: maiRole
  template:
    metadata: 
      labels:
        role: maiRole
    spec:
      containers:
        - name: deploy-container
          image: mprambadi/hello-vue
          ports:
            - containerPort: 80